# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Yunosdklite' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'YunoSDK', '~> 1.0.14'
  use_frameworks!

  # Pods for Yunosdklite

end
